-- xsSplained_mechanics_desc.lua
local mod = get_mod("xsSplained")

local color_utils = mod.color_utils
local CKWord = color_utils.CKWord
local CNumb = color_utils.CNumb
local CPhrs = color_utils.CPhrs
local CNote = color_utils.CNote
local Dot_nc = color_utils.DOT_NC or "•"
local Dot_red = color_utils.DOT_RED or "•"
local Dot_green = color_utils.DOT_GREEN or "•"

local ingame_descriptions = {
strength_ingame_description = {
		en = CKWord("Strength", "Strength_rgb").." (formerly "..CKWord("Power", "Power_rgb")..") is a core combat stat that increases your overall offensive effectiveness.\n"
			.."\n"
			.."What affects:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". "..CKWord("Damage", "Damage_rgb")..": raw "..CKWord("Damage", "Damage_rgb").." output of your Attacks.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". "..CKWord("Stagger", "Stagger_rgb")..": force of your hits - interrupts and controls enemies.\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". "..CKWord("Cleave", "Cleave_rgb")..": number of enemies hit with a single swing.\n"
			.."\n"
			.."Strategic importance:\n"
			..Dot_nc.." Universal bonus - benefits nearly every attack.\n"
			..Dot_nc.." Key for control - higher "..CKWord("Strength", "Strength_rgb").." makes it easier to interrupt dangerous enemies and manage hordes.\n"
			..Dot_nc.." Efficiency - boosts both "..CKWord("Damage", "Damage_rgb").." and "..CKWord("Stagger", "Stagger_rgb")..", letting you kill faster and create safer openings.\n"
			.."\n"
			.."How to increase:\n"
			..Dot_green.." "..CKWord("Combat Stimm", "Combat_Stimm_rgb")..": grants "..CNumb("+", "n_plus_rgb")..CNumb("25%", "pc_25_rgb").." "..CKWord("Strength", "Strength_rgb").." for "..CNumb("15", "n_15_rgb").." seconds.\n"
			..Dot_green.." Class Talents and Blessings: many talents and weapon blessings provide temporary "..CKWord("Strength", "Strength_rgb").." bonuses.",
		ru = CKWord("Сила", "Sila_rgb_ru").." ("..CKWord("Strength", "Strength_rgb")..", ранее "..CKWord("Power", "Power_rgb")..") — базовая боевая характеристика, повышающая общую наступательную эффективность в бою.\n"
			.."\n"
			.."На что влияет:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". "..CKWord("Урон", "uron_rgb_ru")..": непосредственный урон от атак.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". "..CKWord("Ошеломление", "Oshelomlenie_rgb_ru")..": сила ударов — прерывает и контролирует врагов.\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". "..CKWord("Рассечение", "rassechenie_rgb_ru")..": количество врагов, поражаемых одним ударом.\n"
			.."\n"
			.."Стратегическая важность:\n"
			..Dot_nc.." Универсальный бонус — улучшает практически любую атаку.\n"
			..Dot_nc.." Ключ к контролю — высокая Сила облегчает прерывание опасных атак и управление ордами.\n"
			..Dot_nc.." Эффективность — увеличивает и урон, и оглушение, позволяя быстрее убивать и создавать возможности для команды.\n"
			.."\n"
			.."Как увеличить:\n"
			..Dot_green.." "..CKWord("Боевой стимулятор", "Combat_Stimm_rgb_ru")..": даёт "..CNumb("+", "n_plus_rgb")..CNumb("25%", "pc_25_rgb").." к Силе на "..CNumb("15", "n_15_rgb").." секунд.\n"
			..Dot_green.." Таланты классов и благословения: многие таланты и благословения оружия дают временные бонусы к Силе.\n",
	},
	finesse_ingame_description = {
		en = CKWord("Finesse", "Finesse_rgb").." is a weapon stat that enhances Attack speed and the "..CKWord("Damage", "Damage_rgb").." of precision strikes.\n"
			.."\n"
			.."What affects:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Attack Speed: increases the speed of both Light and Heavy Attacks.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". "..CKWord("Finesse Damage", "Finesse_dmg_rgb")..": a multiplier to "..CKWord("Damage", "Damage_rgb").." dealt by "..CKWord("Critical Hits", "Crit_hit_rgb").." and hits to an enemy's "..CKWord("Weak Spot", "Weakspot_rgb")..".\n"
			.."\n"
			.."Strategic importance:\n"
			..Dot_green.." "..CKWord("Finesse", "Finesse_rgb").." is a cornerstone for "..CKWord("Crit", "Crit_rgb").." builds and precision focused classes (Zealot, Veteran). It significantly boosts Blessings and Talents that trigger 'on critical hit' or 'on weak spot hit'.\n"
			.."\n"
			.."How to increase:\n"
			..Dot_green.." Weapon Selection: choose weapons with a naturally high base "..CKWord("Finesse", "Finesse_rgb").." stat.\n"
			..Dot_green.." Weapon Perks and Blessings: some blessings directly increase "..CKWord("Finesse Damage", "Finesse_dmg_rgb").." or "..CKWord("Critical Chance", "Crit_chance_rgb")..".\n"
			..Dot_green.." Class Talents: many talents (especially for Zealot and Veteran) provide conditional boosts to attack speed or "..CKWord("Critical Damage", "Crit_dmg_r_rgb")..".\n"
			.."\n"
			.."Weapon examples:\n"
			..Dot_green.." High "..CKWord("Finesse", "Finesse_rgb").." weapons: Dueling Swords, Combat Blades, Tactical Axes - designed for speed and precision.\n"
			..Dot_red.." Low "..CKWord("Finesse", "Finesse_rgb").." weapons: heavy cleaving weapons like Ogryn Bully Clubs and two handed swords - rely on raw "..CKWord("Damage", "Damage_rgb")..", "..CKWord("Stagger", "Stagger_rgb")..", and crowd control.\n",
		ru = CKWord("Ловкость", "Lovkost_rgb_ru").." — характеристика оружия, которая увеличивает скорость атаки и урон от точных ударов.\n"
			.."\n"
			.."На что влияет:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Скорость атаки: увеличивает скорость как лёгких, так и тяжёлых атак.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". "..CKWord("Урон от ловкости", "lovkosti_uron_rgb_ru")..": множитель урона для "..CKWord("Критических ударов", "krit_udarov_rgb_ru").." и попаданий по "..CKWord("Уязвимым местам", "Ujazvimye_mesta_rgb_ru")..".\n"
			.."\n"
			.."Стратегическая важность:\n"
			..Dot_green.." "..CKWord("Ловкость", "Lovkost_rgb_ru").." — краеугольный камень для "..CKWord("крит-сборок", "Kriticheskie_rgb_ru").." и классов, ориентированных на точность (Изувер, Ветеран). Она значительно повышает эффективность благословений и талантов, срабатывающих 'при критическом ударе' или 'попадании в уязвимое место'.\n"
			.."\n"
			.."Как увеличить:\n"
			..Dot_green.." Выбор оружия: выбирайте оружие с от природы высоким базовым показателем Ловкости.\n"
			..Dot_green.." Перки и благословения оружия: некоторые благословения напрямую увеличивают "..CKWord("урон от ловкости", "lovkosti_uron_rgb_ru").." или "..CKWord("шанс критического удара", "sh_krit_udara_rgb_ru")..".\n"
			..Dot_green.." Таланты классов: многие таланты (особенно у Изувера и Ветерана) дают временные усиления скорости атаки или "..CKWord("критического урона", "krit_uronu_rgb_ru")..".\n"
			.."\n"
			.."Примеры оружия:\n"
			..Dot_green.." Оружие с высокой Ловкостью: дуэльные мечи, боевые клинки, тактические топоры — созданы для скорости и точности.\n"
			..Dot_red.." Оружие с низкой Ловкостью: тяжёлое рубящее оружие, например палицы Огринов и двуручные мечи — полагается на чистый "..CKWord("урон", "uron_rgb_ru")..", "..CKWord("оглушение", "oshelomlenie_rgb_ru").." и контроль толпы.\n",
	},
	health_ingame_description = {
		en = CKWord("Health", "Health_rgb").." - your life pool. Determines how much "..CKWord("Damage", "Damage_rgb").." you can take before being downed. Doesn't regenerate on its own during a mission.\n"
			.."\n"
			..CKWord("Health", "Health_rgb").." is harder to restore during combat than "..CKWord("Toughness", "Toughness_rgb")..". Your Max "..CKWord("Health", "Health_rgb").." varies by class.\n"
			.."\n"
			..CKWord("Wound", "Wound_rgb").." system (downed state):\n"
			..Dot_nc.." Your healthbar is divided into segments called "..CKWord("Wounds", "Wounds_rgb")..".\n"
			..Dot_nc.." First Down: if you get downed and revived, your Max "..CKWord("Health", "Health_rgb").." is reduced by one "..CKWord("Wound", "Wound_rgb").."(becomes "..CKWord("Corrupted", "Corrupted_rgb")..").\n"
			..Dot_red.." True Death: if you are downed with only one remaining "..CKWord("Wound", "Wound_rgb")..", you die instantly and must respawn.\n"
			..Dot_green.." Full Recovery: "..CKWord("Wounds", "Wounds_rgb").." and Max "..CKWord("Health", "Health_rgb").." are fully restored only by using a Medicae Station, a "..CKWord("Med Stimm", "Med_Stimm_rgb")..", or completing the mission.\n"
			.."\n"
			.."Taking "..CKWord("Damage", "Damage_rgb")..":\n"
			..Dot_nc.." When "..CKWord("Toughness", "Toughness_rgb").." is depleted, attacks damage "..CKWord("Health", "Health_rgb")..".\n"
			..Dot_red.." Snipers and Poxbursters bypass "..CKWord("Toughness", "Toughness_rgb").." and damage "..CKWord("Health", "Health_rgb").." directly.\n"
			..Dot_red.." "..CKWord("Corruption", "Corruption_rgb")..": Carrying a grimoire, Pox Hound pinned attacks, Beast of Nurgle's vomit and Chaos Spawn bites apply "..CKWord("Corruption", "Corruption_rgb").." lowering your "..CKWord("Health", "Health_rgb")..".\n"
			.."\n"
			..CKWord("Health", "Health_rgb").." recovery (during a mission):\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Medicae Stations: fully restore all "..CKWord("Health", "Health_rgb").." and clear all "..CKWord("Corrupted", "Corrupted_rgb").." "..CKWord("Wounds", "Wounds_rgb")..".\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". Medipacks (deployable): gradually restore "..CKWord("Health", "Health_rgb").." to all Allies in radius. Cannot remove "..CKWord("Corruption", "Corruption_rgb").." or restore lost "..CKWord("Wounds", "Wounds_rgb")..".\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". "..CKWord("Med Stimm", "Med_Stimm_rgb")..": instantly restores Health equal to one wound or "..CNumb("25%", "pc_25_rgb").." of max "..CKWord("Health", "Health_rgb").." (whichever is greater). Cleanses corruption.\n"
			..Dot_green.." "..CNumb("4", "n_4_rgb")..". Class Talents: some talents provide limited healing (e.g., on kill, when using an ability).\n"
			.."\n"
			.."How to increase Max "..CKWord("Health", "Health_rgb")..":\n"
			..Dot_green.." Curios: equip Curios with the '"..CNumb("+", "n_plus_rgb")..CNumb("%", "pc_rgb").." "..CKWord("Health", "Health_rgb").."' property. Bonuses are additive (three "..CNumb("+", "n_plus_rgb")..CNumb("21%", "pc_21_rgb").." Curios give "..CNumb("+", "n_plus_rgb")..CNumb("63%", "pc_63_rgb").." to base "..CKWord("Health", "Health_rgb")..").\n"
			..Dot_green.." Talents: certain class talents can provide temporary or permanent Max "..CKWord("Health", "Health_rgb").." bonuses.\n"
			.."\n"
			.."CLASS BASE/MAX HEALTH (at level "..CNumb("30", "n_30_rgb").."):\n"
			.."__________________________________\n"
			.."| Class           | Base HP | "..CNumb("3", "n_3_rgb")..CNumb("x", "n_x_rgb").." Curios "..CNumb("+", "n_plus_rgb")..CNumb("21%", "pc_21_rgb").."\n"
			.."__________________________________\n"
			.."| Ogryn          | "..CNumb("300", "n_300_rgb").."        | "..CNumb("489", "n_489_rgb").."\n"
			.."| Zealot          | "..CNumb("200", "n_200_rgb").."        | "..CNumb("326", "n_326_rgb").."\n"
			.."| Arbites        | "..CNumb("200", "n_200_rgb").."        | "..CNumb("326", "n_326_rgb").."\n"
			.."| Veteran       | "..CNumb("150", "n_150_rgb").."         | "..CNumb("245", "n_245_rgb").."\n"
			.."| Psyker         | "..CNumb("150", "n_150_rgb").."         | "..CNumb("245", "n_245_rgb").."\n"
			.."| Hive Scum  | "..CNumb("150", "n_150_rgb").."         | "..CNumb("245", "n_245_rgb").."\n"
			.."__________________________________\n",
		ru = CKWord("Здоровье", "Zdorovie_rgb_ru").." — ваш запас жизней. Определяет, сколько "..CKWord("урона", "urona_rgb_ru").." вы можете получить, прежде чем будете повержены. Не восстанавливается само по себе во время миссии.\n"
			.."\n"
			..CKWord("Здоровье", "Zdorovie_rgb_ru").." восстанавливать в бою сложнее, чем "..CKWord("Стойкость", "Stoikost_rgb_ru")..". Максимум здоровья зависит от класса.\n"
			.."\n"
			.."Система "..CKWord("Ран", "ran_rgb_ru").." (состояние поверженности):\n"
			..Dot_nc.." Ваша полоса здоровья разделена на сегменты — "..CKWord("Раны", "rany_rgb_ru")..".\n"
			..Dot_nc.." Первое падение: если вас повергли и подняли, максимум здоровья уменьшается на одну рану (становится повреждённой/фиолетовой).\n"
			..Dot_red.." Окончательная смерть: если вас повергли с одной оставшейся раной, вы мгновенно умираете и должны возродиться.\n"
			..Dot_green.." Полное восстановление: раны и максимум здоровья полностью восстанавливаются только на Медицинской станции, с помощью "..CKWord("Мед-стима", "Med_Stimm_rgb_ru").." или после завершения миссии.\n"
			.."\n"
			.."Получение "..CKWord("урона", "urona_rgb_ru")..":\n"
			..Dot_nc.." Когда "..CKWord("Стойкость", "Stoikost_rgb_ru").." истощена, атаки наносят урон здоровью.\n"
			..Dot_red.." Снайперы и Взрывуны игнорируют Стойкость и наносят урон здоровью напрямую.\n"
			..Dot_red.." "..CKWord("Порча", "porcha_rgb_ru")..": ношение Гримуара, атаки Пса-отравителя, плевок Чудовища Нургла и укусы Хаосита применяют порчу, снижая ваше здоровье.\n"
			.."\n"
			.."Восстановление здоровья (во время миссии):\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Медицинские станции: полностью восстанавливают всё здоровье и очищают все повреждённые раны.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". Аптечки: постепенно восстанавливают здоровье всем союзникам в радиусе. Не удаляют порчу и не восстанавливают потерянные раны.\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". "..CKWord("Мед-стим", "Med_Stimm_rgb_ru")..": мгновенно восстанавливает здоровье в размере одной раны или 25% от максимума (что больше). Очищает порчу.\n"
			..Dot_green.." "..CNumb("4", "n_4_rgb")..". Таланты классов: некоторые таланты дают ограниченное лечение (например, при убийстве, использовании способности).\n"
			.."\n"
			.."Как увеличить максимум здоровья:\n"
			..Dot_green.." "..CKWord("Редкости", "Curio_p_rgb_ru")..": экипируйте Редкости со свойством '+"..CNumb("%", "pc_rgb").." здоровья'. Бонусы складываются аддитивно (три Редкости по "..CNumb("+21%", "pc_21_rgb").." дают "..CNumb("+63%", "pc_63_rgb").." к базовому здоровью).\n"
			..Dot_green.." Таланты: определённые таланты классов могут давать временные или постоянные бонусы к максимуму здоровья.\n"
			.."\n"
			.."БАЗОВЫЙ/МАКСИМАЛЬНЫЙ УРОВЕНЬ ЗДОРОВЬЯ (уровень "..CNumb("30", "n_30_rgb").."):\n"
			.."__________________________________\n"
			.."| Класс           | База  | "..CNumb("3", "n_3_rgb")..CNumb("x", "n_x_rgb").." Ред. "..CNumb("+21%", "pc_21_rgb").."\n"
			.."__________________________________\n"
			.."| Огрин          | "..CNumb("300", "n_300_rgb").."       | "..CNumb("489", "n_489_rgb").."\n"
			.."| Зилот          | "..CNumb("200", "n_200_rgb").."       | "..CNumb("326", "n_326_rgb").."\n"
			.."| Арбитр         | "..CNumb("200", "n_200_rgb").."       | "..CNumb("326", "n_326_rgb").."\n"
			.."| Ветеран        | "..CNumb("150", "n_150_rgb").."        | "..CNumb("245", "n_245_rgb").."\n"
			.."| Псайкер        | "..CNumb("150", "n_150_rgb").."        | "..CNumb("245", "n_245_rgb").."\n"
			.."| Отребье Улья   | "..CNumb("150", "n_150_rgb").."        | "..CNumb("245", "n_245_rgb").."\n"
			.."__________________________________\n",
	},
	toughness_ingame_description = {
		en = CKWord("Toughness", "Toughness_rgb").." — your primary defense, a rechargeable shield that protects your "..CKWord("Health", "Health_rgb")..".\n"
			.."\n"
			.."Core Mechanics:\n"
			..Dot_green.." Ranged attacks: With any "..CKWord("Toughness", "Toughness_rgb").." "..CNumb(">", "n_greater_rgb").." "..CNumb("0", "n_0_rgb")..", you take "..CNumb("100%", "pc_100_rgb").." reduced "..CKWord("Damage", "Damage_rgb").." from Ranged attacks.\n"
			..Dot_green.." Melee attacks: The "..CNumb("%", "pc_rgb").." of blocked Melee "..CKWord("Damage", "Damage_rgb").." equals your current "..CKWord("Toughness", "Toughness_rgb").." percentage (e.g., "..CNumb("80%", "pc_80_rgb").." "..CKWord("Toughness", "Toughness_rgb").." blocks "..CNumb("80%", "pc_80_rgb").." of "..CKWord("Damage", "Damage_rgb")..", but "..CNumb("20%", "pc_20_rgb").." bypasses to "..CKWord("Health", "Health_rgb")..").\n"
			.."\n"
			.."Critical Interactions:\n"
			..Dot_red.." Direct "..CKWord("Damage", "Damage_rgb").." attacks: Sniper shots and Poxburster explosions bypass "..CKWord("Toughness", "Toughness_rgb").." and "..CKWord("Damage", "Damage_rgb").." "..CKWord("Health", "Health_rgb").." directly.\n"
			..Dot_green.." "..CKWord("Toughness", "Toughness_rgb").." Gate: Having at least 1 point of Toughness prevents you from being one-shot, even if the raw "..CKWord("Damage", "Damage_rgb").." exceeds your remaining "..CKWord("Health", "Health_rgb")..".\n"
			.."\n"
			.."How to Regenerate "..CKWord("Toughness", "Toughness_rgb")..":\n"
			..Dot_green.." "..CKWord("Coherency", "Coherency_rgb")..": Passively regenerates "..CKWord("Toughness", "Toughness_rgb").." over time when near teammates. The more Allies in "..CKWord("Coherency", "Coherency_rgb")..", the faster the regeneration.\n"
			..Dot_green.." Melee kills: Killing an enemy in Melee restores a base amount ("..CNumb("5%", "pc_5_rgb")..") of "..CKWord("Toughness", "Toughness_rgb")..". Many Talents and Blessings increase this value.\n"
			..Dot_green.." Class Talents and Abilities: Many talents provide conditional "..CKWord("Toughness", "Toughness_rgb").." regeneration (e.g., on Elite kills, Ability use, or over time).\n"
			..Dot_green.." Curios: Can provide bonuses like "..CNumb("+", "n_plus_rgb")..CKWord("Toughness", "Toughness_rgb")..CNumb("%", "pc_rgb")..", "..CNumb("+", "n_plus_rgb")..CKWord("Toughness", "Toughness_rgb").." Regeneration Speed, or "..CNumb("+", "n_plus_rgb")..CKWord("Toughness Damage Reduction", "Tghns_dmg_red_rgb")..".\n"
			.."\n"
			.."Key Stats:\n"
			..Dot_green.." "..CKWord("Golden Toughness", "Tghness_gold_rgb")..": A special overshield that can exceed "..CNumb("100%", "pc_100_rgb").." "..CKWord("Toughness", "Toughness_rgb")..", rendering you immune to all "..CKWord("Damage", "Damage_rgb").." until depleted.\n"
			..Dot_green.." "..CKWord("Toughness Damage Reduction", "Tghns_dmg_red_rgb")..": Reduces the amount of "..CKWord("Toughness", "Toughness_rgb").." lost when taking "..CKWord("Damage", "Damage_rgb")..". Essential for survivability.",
		ru = CKWord("Стойкость", "Stoikost_rgb_ru").." — ваша основная защита, перезаряжаемый щит, который охраняет Здоровье.\n"
			.."\n"
			.."Основная механика:\n"
			..Dot_green.." Атаки дальнего боя: при любом количестве Стойкости > 0 вы получаете на 100% меньше урона от дальнобойных атак.\n"
			..Dot_green.." Атаки ближнего боя: процент заблокированного урона равен текущему проценту Стойкости (например, 80% Стойкости блокирует 80% урона, но 20% проходит в здоровье).\n"
			.."\n"
			.."Критичные взаимодействия:\n"
			..Dot_red.." Атаки прямого урона: выстрелы снайперов и взрывы Взрывунов игнорируют Стойкость и наносят урон здоровью напрямую.\n"
			..Dot_green.." Щит Стойкости: наличие хотя бы 1 единицы Стойкости предотвращает мгновенную смерть с одного удара, даже если урон превышает оставшееся здоровье.\n"
			.."\n"
			.."Как восстанавливать Стойкость:\n"
			..Dot_green.." "..CKWord("Согласованность", "splochennosti_rgb_ru")..": пассивное восстановление с течением времени, когда вы рядом с союзниками. Чем больше союзников рядом, тем быстрее восстановление.\n"
			..Dot_green.." Убийства в ближнем бою: убийство врага в ближнем бою восстанавливает базовые "..CNumb("5%", "pc_5_rgb").." Стойкости. Многие таланты и благословения увеличивают это значение.\n"
			..Dot_green.." Таланты и способности классов: многие таланты дают условное восстановление Стойкости (например, за убийство элит, использование способности или с течением времени).\n"
			..Dot_green.." "..CKWord("Редкости", "Curio_p_rgb_ru")..": могут давать бонусы, такие как "..CNumb("+", "n_plus_rgb")..CKWord("Стойкость", "Stoikost_rgb_ru")..CNumb("%", "pc_rgb")..", "..CNumb("+", "n_plus_rgb").." скорость восстановления Стойкости или "..CNumb("+", "n_plus_rgb")..CKWord("Снижение урона по стойкости", "snu_ur_stoikosti_rgb_ru")..".\n"
			.."\n"
			.."Ключевые статы:\n"
			..Dot_green.." "..CKWord("Золотая стойкость", "Stojkost_Zolot_rgb_ru")..": особый сверхщит, который может превышать 100% Стойкости, делая вас полностью неуязвимым для любого урона, пока он активен.\n"
			..Dot_green.." "..CKWord("Снижение урона по стойкости", "snu_ur_stoikosti_rgb_ru")..": уменьшает количество теряемой Стойкости при получении урона. Крайне важно для выживания.\n",
	},
	stamina_ingame_description = {
		en = CKWord("Stamina", "Stamina_rgb").." - determines your ability to perform actions such as Sprinting, Blocking, and Pushing.\n"
			.."\n"
			.."Core mechanics:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Sprinting: Continuous sprinting drains "..CKWord("Stamina", "Stamina_rgb").." over time.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". Blocking: Each blocked attack consumes "..CKWord("Stamina", "Stamina_rgb").." based on the attack's strength.\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". Pushing: Performing a push or push-attack costs "..CKWord("Stamina", "Stamina_rgb")..".\n"
			.."\n"
			.."Why it matters:\n"
			..Dot_nc.." Proper "..CKWord("Stamina", "Stamina_rgb").." management is crucial for survival in Melee combat.\n"
			..Dot_red.." Running out of "..CKWord("Stamina", "Stamina_rgb").." leaves you vulnerable to enemy attacks.\n"
			..Dot_nc.." Different weapons have varying "..CKWord("Stamina", "Stamina_rgb").." costs and regeneration rates.\n"
			.."\n"
			..CKWord("Stamina", "Stamina_rgb").." Regeneration:\n"
			..Dot_green.." Regenerates automatically after a brief pause ("..CNumb("~0.85", "n__0_85_rgb").." seconds) once you stop actively consuming it for Blocks, Pushes, or Sprinting.\n"
			..Dot_green.." Some Talents and Curios can improve "..CKWord("Stamina", "Stamina_rgb").." regeneration or decrease consuming.\n"
			..Dot_red.." Dodging briefly pauses "..CKWord("Stamina", "Stamina_rgb").." regeneration. It's not always correct to begin dodging immediately.\n"
			.."\n"
			.."Tactical insights:\n"
			..Dot_green.." Dodging vs. Blocking: Timely dodging is often more reliable than Blocking. Use Blocking as a backup.\n"
			..Dot_green.." Resource Management: Sprinting depletes the same "..CKWord("Stamina", "Stamina_rgb").." pool used for pushes. Manage it wisely.",
		ru = CKWord("Выносливость", "Vynoslivost_rgb_ru").." - определяет вашу способность выполнять действия, такие как бег, блокирование и толчки.\n"
			.."\n"
			.."Основная механика:\n"
			..Dot_green.." "..CNumb("1", "n_1_rgb")..". Бег: непрерывный бег истощает "..CKWord("Выносливость", "Vynoslivost_rgb_ru").." со временем.\n"
			..Dot_green.." "..CNumb("2", "n_2_rgb")..". Блокирование: каждая заблокированная атака потребляет "..CKWord("Выносливость", "Vynoslivost_rgb_ru").." в зависимости от силы атаки.\n"
			..Dot_green.." "..CNumb("3", "n_3_rgb")..". Толчки: выполнение толчка или атаки с толчком стоит "..CKWord("Выносливости", "vynoslivosti_rgb_ru")..".\n"
			.."\n"
			.."Почему это важно:\n"
			..Dot_nc.." Правильное управление "..CKWord("Выносливостью", "vynoslivosti_rgb_ru").." крайне важно для выживания в ближнем бою.\n"
			..Dot_red.." Истощение "..CKWord("Выносливости", "vynoslivosti_rgb_ru").." оставляет вас уязвимым для вражеских атак.\n"
			..Dot_nc.." Разное оружие имеет различную стоимость "..CKWord("Выносливости", "vynoslivosti_rgb_ru").." и скорость восстановления.\n"
			.."\n"
			.."Восстановление "..CKWord("Выносливости", "vynoslivosti_rgb_ru")..":\n"
			..Dot_green.." Восстанавливается автоматически после короткой паузы ("..CNumb("~0.85", "n__0_85_rgb").." секунды), когда вы перестаете активно тратить её на блоки, толчки или бег.\n"
			..Dot_green.." Некоторые таланты и Редкости могут улучшить восстановление "..CKWord("Выносливости", "vynoslivosti_rgb_ru").." или снизить её потребление.\n"
			..Dot_red.." Уклонение ненадолго останавливает восстановление "..CKWord("Выносливости", "vynoslivosti_rgb_ru")..". Начинать уклонение немедленно — не всегда правильно.\n"
			.."\n"
			.."Тактические советы:\n"
			..Dot_green.." Уворот против блока: своевременное уклонение часто надёжнее блокирования. Используйте блок как запасной вариант.\n"
			..Dot_green.." Управление ресурсами: бег истощает тот же запас "..CKWord("Выносливости", "vynoslivosti_rgb_ru")..", что и толчки. Управляйте им с умом.\n",
	},
	cleave_ingame_description = {
		en = "Cleave determines how many enemies your attack can pass through before losing effectiveness. It's a core stat for crowd control.\n"
			.."\n"
			.."Core Mechanics:\n"
			.."  • Cleave vs. Hit Mass: Your attack's cleave value is a 'budget'. Each enemy hit consumes part of it based on their Hit Mass (e.g., Poxwalker=1.25, Mauler=10). The attack stops when the budget reaches zero.\n"
			.."  • Separate Values: A weapon has distinct values for 'Damage Cleave' and 'Stagger Cleave'. You can often stagger more enemies than you damage in one swing.\n"
			.."  • Damage Distribution: Damage is not equal for all targets and depends on the attack type.\n"
			.."     - Strikedown (e.g., heavy overhead): 100% to first target, ~25% to second, then stops.\n"
			.."     - Sweeping (e.g., wide horizontal): Distributes more evenly (e.g., 100%, 75%, 50%).\n"
			.."\n"
			.."Key Interactions and Limitations:\n"
			.."  • Armor Stop: Carapace armor (Crushers) COMPLETELY stops cleave, unless bypassed by specific blessings (Sunder, Perfect Strike) or weapon effects (Plasma Gun).\n"
			.."  • Stagger Synergy: Staggering an enemy reduces its Hit Mass for cleave calculation: Light -10%, Medium -25%, Heavy -50%. This lets you hit more targets.\n"
			.."  • Difficulty Scaling: Enemy Hit Mass increases on higher difficulties, making Cleave less effective against hordes.\n"
			.."  • Ignoring Hit Mass: Blessings like Brutal Momentum (after a weak spot kill) or Devastating Strike (on crit) can temporarily ignore Hit Mass, allowing attacks to pass through enemies freely.\n"
			.."\n"
			.."Strategic Importance:\n"
			.."  • Horde Control: Essential for controlling dense groups. High cleave weapons (e.g., two-handed swords) excel here.\n"
			.."  • Target Priority: The order matters. Hitting a high-mass enemy (like a Mauler) first will stop your swing early. Aim to clear weaker foes first.\n"
			.."  • Weapon and Build Choice: The 'Crowd Control' modifier directly increases Cleave, Impact, and Stagger. Builds focusing on Stagger indirectly improve cleave efficiency.\n"
			.."\n"
			.."Testing and Resources:\n"
			.."  The best way to understand your weapon's cleave is to test it in the Psykhanium against different enemy types. For detailed stats and breakpoints, the community uses specialized calculators.",
		ru = "Рассечение определяет, сквозь скольких врагов может пройти ваша атака до потери эффективности. Это ключевая характеристика для контроля толпы.\n"
			.."\n"
			.."Основная механика:\n"
			.."  • Клив против Ударной массы: Значение клива вашей атаки — это «бюджет». Каждый пораженный враг расходует его часть в зависимости от своей Ударной массы (например, Чумной=1.25, Крушитель=10). Атака останавливается, когда бюджет достигает нуля.\n"
			.."  • Раздельные значения: У оружия есть отдельные значения «Клива урона» и «Клива оглушения». Часто можно оглушить больше врагов, чем нанести урон одним взмахом.\n"
			.."  • Распределение урона: Урон не одинаков для всех целей и зависит от типа атаки.\n"
			.."     - Рубящий удар (сверху вниз): 100% первому, ~25% второму, затем остановка.\n"
			.."     - Размашистый удар (горизонтальный): Распределение более равномерное (напр., 100%, 75%, 50%).\n"
			.."\n"
			.."Ключевые взаимодействия и ограничения:\n"
			.."  • Остановка бронёй: Броня типа Carapace (Крестоносцы) ПОЛНОСТЬЮ останавливает клив, если только его не обходят особые благословения (Sunder, Perfect Strike) или эффекты оружия (Плазмаган).\n"
			.."  • Синергия с оглушением: Оглушение врага снижает его Ударную массу для расчёта клива: Лёгкое -10%, Среднее -25%, Тяжёлое -50%. Это позволяет поразить больше целей.\n"
			.."  • Влияние сложности: На высоких уровнях сложности Ударная масса врагов увеличивается, снижая эффективность клива против орд.\n"
			.."  • Игнорирование массы: Благословения вроде Жестокого импульса (после убийства в уязвимое место) или Сокрушительного удара (при крите) могут временно игнорировать Ударную массу, позволяя атаке свободно проходить сквозь врагов.\n"
			.."\n"
			.."Стратегическая важность:\n"
			.."  • Контроль орды: Критически важно для управления плотными группами. Оружие с высоким кливом (двуручные мечи) здесь превосходно.\n"
			.."  • Приоритет целей: Порядок имеет значение. Попадание по врагу с высокой массой (Крушителю) первым остановит ваш взмах. Старайтесь сначала поражать слабых врагов.\n"
			.."  • Выбор оружия и сборки: Модификатор 'Контроль толпы' напрямую увеличивает Клив, Силу воздействия и Оглушение. Сборки, фокусирующиеся на оглушении, косвенно улучшают эффективность клива.\n"
			.."\n"
			.."Тестирование и ресурсы:\n"
			.."  Лучший способ понять клив вашего оружия — протестировать его в Психаниуме против разных типов врагов. Для детальных характеристик сообщество использует специализированные калькуляторы."
	},
	crit_chance_ingame_description = {
		en = "Critical Hit Chance - determines the probability of an attack becoming a Critical Hit.\n"
			.."\n"
			.."Core Mechanics:\n"
			.."  • Base Values: All classes have a base 5% Critical Chance and a base +25% Critical Damage multiplier.\n"
			.."  • Roll Per Attack: The chance is calculated once per attack animation (swing, shot, explosion), not per enemy hit. A successful crit applies to all targets hit by that single attack.\n"
			.."  • Crit Batching (Ranged): On rapid-fire weapons, a single crit trigger grants multiple consecutive critical hits. The number is fixed per weapon type (e.g., 2 for Recon Lasgun, 6 for Ogryn Heavy Stubber). This makes even a low crit chance extremely valuable on such weapons.\n"
			.."  • Modifiers: Crit chance can be increased by the Finesse stat, Perks (+5% max), Blessings, and Talents (e.g., Zealot's Chastise the Wicked). Some weapons have temporary conditional bonuses.\n"
			.."\n"
			.."Effects of a Critical Hit:\n"
			.."  1. Increased Damage: Adds a flat +25% multiplier to your attack's total damage (modified by talents/blessings).\n"
			.."  2. Triggers Special Effects: The primary value. Activates talents and blessings that work 'on critical hit' (e.g., applying Bleed, restoring Toughness, ignoring Hit Mass with Brutal Momentum).\n"
			.."  3. Enhanced Status Effects: For weapons applying Damage Over Time (DoT), like Flamers, a critical hit applies two stacks of the effect instead of one.\n"
			.."\n"
			.."Important Clarifications:\n"
			.."  • Crits ≠ Weak Spot Hits: These are separate mechanics. Hitting a weak spot (like the head) does NOT guarantee a critical hit, and a critical hit does NOT automatically target a weak spot.\n"
			.."  • Armor Penetration: Critical hits do NOT inherently ignore armor. Certain blessings or talents may grant armor penetration specifically on crits, but this is not a universal rule.\n"
			.."  • Guaranteed Crits: Effects from talents or abilities that guarantee critical hits (e.g., Zealot's Dash) are applied as temporary buffs and are not reflected in the standard crit chance calculation.\n"
			.."\n"
			.."Tactical Value and Builds:\n"
			.."  Crit chance is a cornerstone for 'on crit' effect builds. It is exceptionally powerful on high-rate-of-fire weapons due to crit batching and on weapons that apply damaging status effects. However, for raw damage output against specific tough targets, dedicated damage perks (like +Flak or +Maniac) are often more reliable and efficient.\n"
			.."\n"
			.."Visual and Audio Feedback:\n"
			.."  • Distinct, sharper sound effect on hit.\n"
			.."  • Larger, orange damage numbers (compared to yellow for weak spots).\n"
			.."  • More pronounced visual effects (sparks, brighter hit markers).",
		ru = "Шанс критического удара - определяет вероятность того, что атака станет критическим ударом.\n"
			.."\n"
			.."Основная механика:\n"
			.."  • Базовые значения: Все классы имеют базовый 5% шанс критического удара и базовый множитель критического урона +25%.\n"
			.."  • Проверка на атаку: Шанс рассчитывается один раз за анимацию атаки (взмах, выстрел, взрыв), а не для каждого поражённого врага. Успешный крит применяется ко всем целям, поражённым этой одной атакой.\n"
			.."  • Пакетные криты (Дальний бой): На скорострельном оружии одно срабатывание шанса крита даёт несколько критических попаданий подряд. Их количество фиксировано для типа оружия (например, 2 у Разведывательного лазгана, 6 у Тяжёлого стаббера Огрина). Это делает даже низкий шанс крита чрезвычайно ценным на таком оружии.\n"
			.."  • Модификаторы: Шанс крита увеличивают характеристика Ловкость (Finesse), Перки (макс. +5%), Благословения и Таланты (например, Увещевание Грешного у Зилота). У некоторых видов оружия есть временные условные бонусы.\n"
			.."\n"
			.."Эффекты критического удара:\n"
			.."  1. Повышенный урон: Добавляет фиксированный множитель +25% к общему урону вашей атаки (может быть увеличен талантами/благословениями).\n"
			.."  2. Активация особых эффектов: Основная ценность. Запускает таланты и благословения, срабатывающие 'при критическом ударе' (например, наложение Кровотечения, восстановление Стойкости, игнорирование Ударной массы с Жестоким импульсом).\n"
			.."  3. Усиленные эффекты статуса: Для оружия, наносящего периодический урон (DoT), например, огнемётов, критический удар накладывает два стака эффекта вместо одного.\n"
			.."\n"
			.."Важные уточнения:\n"
			.."  • Криты ≠ попадания в уязвимые места: Это разные механики. Попадание в уязвимое место (например, в голову) НЕ гарантирует критический удар, а критический удар НЕ обязательно поражает уязвимое место.\n"
			.."  • Пробитие брони: Критические удары сами по себе НЕ игнорируют броню. Определённые благословения или таланты могут давать пробитие брони именно при критах, но это не общее правило.\n"
			.."  • Гарантированные криты: Эффекты талантов или способностей, гарантирующие критический удар (например, Рывок Зилота), применяются как временные усиления и не учитываются в стандартном расчёте шанса крита.\n"
			.."\n"
			.."Тактическая ценность и сборки:\n"
			.."  Шанс крита — краеугольный камень для сборок, ориентированных на эффекты 'при крите'. Он исключительно силён на скорострельном оружии благодаря пакетным критам и на оружии, наносящем урон статусами. Однако для чистого урона по конкретным крепким целям специализированные перки на урон (например, +Flak или +Maniac) часто надёжнее и эффективнее.\n"
			.."\n"
			.."Визуальная и звуковая обратная связь:\n"
			.."  • Отчётливый, более резкий звук при попадании.\n"
			.."  • Крупные оранжевые цифры урона (в отличие от жёлтых для уязвимых мест).\n"
			.."  • Более выраженные визуальные эффекты (искры, яркие маркеры попадания)."
	},
	impact_ingame_description = {
		en = "Impact - a hidden stat that determines the force of your attack, influencing its ability to stagger and control enemies.\n"
			.."\n"
			.."Core Function:\n"
			.."  • Each attack has an Impact value.\n"
			.."  • This value is checked against the enemy's Stagger Resistance threshold.\n"
			.."  • If the Impact exceeds the threshold, the enemy is staggered.\n"
			.."  • The degree of stagger (light/medium/heavy) and its duration/distance scale with how much you exceed the threshold.\n"
			.."\n"
			.."Stagger Thresholds (Examples):\n"
			.."  • Light Stagger: ~1 Impact\n"
			.."  • Medium Stagger: ~10 Impact\n"
			.."  • Heavy Stagger (Knockdown): ~20 Impact\n"
			.."\n"
			.."Key Interaction: Impact and Stagger as Resources\n"
			.."  • Your weapon's Stagger Cleave is a separate 'budget' that determines how many enemies you can affect with stagger in one swing.\n"
			.."  • Impact is the 'strength' applied to each staggered enemy.\n"
			.."  • High-Impact attacks can stagger tougher enemies but may have lower Stagger Cleave.\n"
			.."\n"
			.."Connection to Stopping Power:\n"
			.."  • The 'Stopping Power' weapon modifier directly increases your Impact and Stagger.\n"
			.."  • 'Collateral' and 'Crowd Control' modifiers also enhance these stats.\n"
			.."  • Combat Stimm increases Impact (stagger strength) by 25% for its duration.\n"
			.."\n"
			.."Tactical Insight:\n"
			.."  Higher Impact means more reliable interruption of enemy attacks, better crowd control, and longer windows of vulnerability for heavy targets. It is a core survival tool, not just a secondary effect.",
		ru = "Выведение из равновесия (Impact) - скрытая характеристика, определяющая силу вашей атаки и её способность ошеломить и контролировать врагов.\n"
			.."\n"
			.."Основная функция:\n"
			.."  • Каждая атака имеет значение Impact (Силы воздействия).\n"
			.."  • Это значение проверяется против порога Сопротивления оглушению (Stagger Resistance) врага.\n"
			.."  • Если Impact превышает порог, враг ошеломляется.\n"
			.."  • Степень оглушения (лёгкое/среднее/тяжёлое) и его длительность/дистанция зависят от того, насколько вы превысили порог.\n"
			.."\n"
			.."Пороги оглушения (примеры):\n"
			.."  • Лёгкое оглушение: ~1 Impact\n"
			.."  • Среднее оглушение: ~10 Impact\n"
			.."  • Тяжёлое оглушение (сбивание с ног): ~20 Impact\n"
			.."\n"
			.."Ключевое взаимодействие: Impact и оглушение как ресурсы\n"
			.."  • Показатель 'Клив оглушения' (Stagger Cleave) вашего оружия — это отдельный «бюджет», определяющий, скольких врагов вы можете задеть оглушением за один взмах.\n"
			.."  • Impact — это «сила», которая применяется к каждому ошеломлённому врагу.\n"
			.."  • Атаки с высоким Impact могут оглушить более крепких врагов, но часто имеют меньший Клив оглушения.\n"
			.."\n"
			.."Связь с Силой удара (Stopping Power):\n"
			.."  • Модификатор оружия 'Сила удара' (Stopping Power) напрямую увеличивает ваши Impact и оглушение.\n"
			.."  • Модификаторы 'Побочный ущерб' (Collateral) и 'Контроль толпы' (Crowd Control) также улучшают эти характеристики.\n"
			.."  • Боевой стимулятор (Combat Stimm) увеличивает Impact (силу оглушения) на 25% на время действия.\n"
			.."\n"
			.."Тактическая подсказка:\n"
			.."  Высокий Impact означает более надёжное прерывание вражеских атак, лучший контроль толпы и более длительные окна уязвимости для тяжёлых целей. Это базовый инструмент выживания, а не просто побочный эффект."
	},
	hitmass_ingame_description = {
		en = "Hit mass - a core, hidden value that determines how many enemies your attack can penetrate.\n"
			.."\n"
			.."Core Mechanics (How It Works):\n"
			.."  1. Consumable Resource: Each attack has a 'cleave value' (like a budget). Every enemy hit subtracts its Hit Mass from this value.\n"
			.."  2. Attack Stop Condition: Your swing stops when the total Hit Mass of enemies hit equals or exceeds your cleave value.\n"
			.."  3. Separate Values: 'Damage Cleave' and 'Stagger Cleave' are different stats. A weapon can often stagger more enemies than it damages.\n"
			.."\n"
			.."Enemy Hit Mass Examples:\n"
			.."  • Low: Poxwalkers (~1.25), basic cultists.\n"
			.."  • Medium: Shooters, Bruisers, Scab Ragers.\n"
			.."  • High: Maulers (~10), Ogryn Bulwark (~12.5), Crushers, Monstrosities (Daemonhost ~20).\n"
			.."\n"
			.."Key Interactions:\n"
			.."  • Ignoring Hit Mass: Blessings like 'Brutal Momentum' or 'Devastating Strike' can treat enemy Hit Mass as 0, granting unlimited cleave for a short time. This is fundamentally different from simply increasing your cleave stat.\n"
			.."  • Stagger Reduces Mass: Successfully staggering an enemy temporarily lowers its Hit Mass, allowing your attacks to cleave through it more easily. This synergizes with stagger-focused builds.\n"
			.."  • Order Matters: The sequence in which you hit enemies is crucial. Hitting a high-mass enemy like a Mauler first will stop your swing, while hitting it last after clearing weaker foes allows you to damage it.\n"
			.."\n"
			.."Tactical Application:\n"
			.."  • Target Priority: Attack angles and target selection are critical. Always try to hit low-mass enemies first to maximize your cleave.\n"
			.."  • Weapon Synergy: 'Ignore Hit Mass' effects are incredibly powerful on weapons with naturally low cleave (like axes), transforming them into exceptional horde-clearing tools.\n"
			.."  • Team Play: Note that effects that reduce an enemy's Hit Mass (e.g., '-30% enemy hit mass on kill') usually only benefit you, not your teammates.\n"
			.."  • Potential Bug: On specific weapons like the Chainsword, the 'Ignore Hit Mass on Critical Hit' blessing has been reported to interfere with its special 'revved' attack, potentially making it deal minimal damage.",
		ru = "Ударная масса - скрытое базовое значение, определяющее, сквозь скольких врагов может пройти ваша атака.\n"
			.."\n"
			.."Основная механика (как это работает):\n"
			.."  1. Расходуемый ресурс: Каждая атака имеет «значение клива» (как бюджет). Каждый пораженный враг вычитает из него свою Ударную массу.\n"
			.."  2. Условие остановки атаки: Ваш взмах останавливается, когда суммарная Ударная масса пораженных врагов достигает или превышает значение вашего клива.\n"
			.."  3. Разные значения: «Клив урона» и «Клив оглушения» — это разные характеристики. Оружие часто может оглушить больше врагов, чем нанести им урон.\n"
			.."\n"
			.."Примеры Ударной массы врагов:\n"
			.."  • Низкая: Чумные (~1.25), базовые культисты.\n"
			.."  • Средняя: Стрелки (Shooters), Громилы (Bruisers), Яростные (Ragers).\n"
			.."  • Высокая: Крушители (~10), Огрин-Булварк (~12.5), Крестоносцы, Чудовища (Демонхост ~20).\n"
			.."\n"
			.."Ключевые взаимодействия:\n"
			.."  • Игнорирование Ударной массы: Благословения вроде «Жестокого импульса» (Brutal Momentum) могут считать Ударную массу врагов равной 0, давая на время неограниченный клив. Это коренным образом отличается от простого увеличения показателя клива.\n"
			.."  • Оглушение снижает массу: Успешное оглушение врага временно снижает его Ударную массу, позволяя вашим атакам легче пробиваться сквозь него. Это создает синергию со сборками, ориентированными на оглушение.\n"
			.."  • Порядок имеет значение: Последовательность, в которой вы поражаете врагов, критична. Попадание по врагу с высокой массой (как Крушитель) первым же остановит ваш взмах, тогда как попадание по нему в конце, после слабых врагов, позволит вам нанести ему урон.\n"
			.."\n"
			.."Тактическое применение:\n"
			.."  • Приоритет целей: Углы атаки и выбор цели критичны. Всегда старайтесь бить сначала по врагам с низкой массой, чтобы максимизировать клив.\n"
			.."  • Синергия с оружием: Эффекты игнорирования массы невероятно сильны на оружии с от природы низким кливом (например, топоры), превращая его в исключительный инструмент зачистки орд.\n"
			.."  • Командная игра: Учитывайте, что эффекты, снижающие Ударную массу врага (например, «-30% к ударной массе врага при убийстве»), обычно работают только на вас, а не на ваших союзников.\n"
			.."  • Потенциальная ошибка: На конкретном оружии, таком как Цепной меч (Chainsword), сообщалось, что благословение «Игнорировать ударную массу при критическом ударе» мешает его особой атаке с «раскруткой» (revved), потенциально заставляя её наносить минимальный урон."
	},
	stagger_ingame_description = {
		en = "Stagger - a core mechanic for interrupting, controlling, and displacing enemies.\n"
			.."\n"
			.."Mechanics and Visual Feedback:\n"
			.."  • Stagger is determined by a hidden 'Impact' value of your attack versus enemy 'Stagger Resistance'.\n"
			.."  • Successfully staggering an enemy temporarily reduces their Hit Mass, improving your attacks' Cleave against them.\n"
			.."  • Some elite enemies gain brief Stagger immunity after being knocked down.\n"
			.."\n"
			.."Strategic Application:\n"
			.."  1. Interrupt Deadly Attacks: Essential for stopping specials (Pox Hound leap, Trapper net).\n"
			.."  2. Control Enemy Density: Staggering front-line enemies reduces their mass, allowing your strikes to cleave deeper into hordes.\n"
			.."  3. Enable Team Damage: A downed enemy (Knockdown) is a vulnerable target for the entire squad.\n"
			.."  4. Defensive Utility: Can instantly free allies pinned by specials (e.g., Pox Hound, Mutant).\n"
			.."  5. Manage Elites: Use heavy staggers to break enemy formations and create openings against armored foes.\n"
			.."\n"
			.."Key Interaction - Stagger vs. Stun:\n"
			.."  • Stun is a separate, longer-lasting immobilizing effect (e.g., from electric shocks).\n"
			.."  • While different, a stunned enemy is also considered 'staggered' for the purpose of triggering related talents and blessings.\n"
			.."\n"
			.."Notable Sources:\n"
			.."  • Melee: Pushes, heavy attacks, high-impact weapons (Thunder Hammer, Power Maul).\n"
			.."  • Ranged: Shotguns, Revolvers, explosives, and force weapons.\n"
			.."  • Abilities: Many class talents (e.g., Zealot's Chastise the Wicked, Ogryn's Bull Rush).\n"
			.."  • Combat Stimm: Increases stagger strength by 25% for 15 seconds.\n",
		ru = "Ошеломление - базовая механика для прерывания, контроля и смещения врагов.\n"
			.."\n"
			.."Механика и визуальные эффекты:\n"
			.."  • Оглушение определяется скрытым значением 'Силы удара' (Impact) вашей атаки и 'Сопротивлением оглушению' врага.\n"
			.."  • Успешное оглушение временно снижает 'Массу' (Hit Mass) врага, улучшая пробивную способность (Cleave) ваших последующих атак по этой цели.\n"
			.."  • Некоторые элитные враги получают кратковременный иммунитет к оглушению после сбивания с ног.\n"
			.."\n"
			.."Стратегическое применение:\n"
			.."  1. Прерывание опасных атак: Критически важно для остановки спецврагов (прыжок Токсичного Пса, сеть Охотника).\n"
			.."  2. Контроль плотности врагов: Оглушение передних рядов снижает их массу, позволяя вашим ударам пробивать дальше в толпу.\n"
			.."  3. Открытие врагов для команды: Сбитый с ног враг становится уязвимой мишенью для всего отряда.\n"
			.."  4. Защита союзников: Может мгновенно освободить союзника, захваченного спецврагом (например, Псом или Мутантом).\n"
			.."  5. Борьба с элитами: Используйте сильное оглушение, чтобы сломать вражеский строй и создать возможности для атаки по бронированным целям.\n"
			.."\n"
			.."Важное взаимодействие - Оглушение (Stagger) vs. Стан (Stun):\n"
			.."  • Стан (Stun) — это отдельный, более долгий эффект обездвиживания (например, от электрошока).\n"
			.."  • Несмотря на различия, оглушённый (stunned) враг также считается 'ошеломлённым' (staggered) для активации связанных талантов и благословений.\n"
			.."\n"
			.."Основные источники:\n"
			.."  • Ближний бой: Толчки, тяжёлые атаки, оружие с высокой ударной силой (Молот Грома, Силовая палица).\n"
			.."  • Дальний бой: Дробовики, Револьверы, взрывчатка и силовое оружие.\n"
			.."  • Способности: Многие таланты классов (например, Увещевание Грешного у Зилота, Буйный Натиск у Огрина).\n"
			.."  • Боевой стимулятор (Combat Stimm): Увеличивает силу оглушения на 25% на 15 секунд.\n"
	},
	weakspot_ingame_description = {
		en = "Weak spots - specific areas on enemies that take increased damage when hit.\n"
			.."\n"
			.."Primary Weak Spot Location:\n"
			.."	  • Head (for the vast majority of humanoid and non-boss enemies).\n"
			.."	  • Special weak spots exist only on certain monstrosities (e.g., Beast of Nurgle's back).\n"
			.."\n"
			.."Crucial Tactical Note:\n"
			.."	  The head is NOT always the best target. Some heavily armored enemies like Maulers and Crushers have Carapace armor on their heads. Against them, hitting the body (Flak armor) or legs (Unarmored) with certain weapons may be more effective.\n"
			.."\n"
			.."Weak Spot Benefits:\n"
			.."	  1. Increased Damage - Multiplier varies significantly by weapon.\n"
			.."	  2. Stagger - Often causes additional stagger.\n"
			.."	  3. Special Effects - Can trigger specific blessings and talents.\n"
			.."\n"
			.."Weak Spot Indicators:\n"
			.."	  • Yellow damage numbers (the primary indicator).\n"
			.."	  • Different hit sound and crosshair feedback.\n"
			.."\n"
			.."Testing is Key:\n"
			.."	  Use the Psykhanium to test your weapon's weak spot damage multipliers against different armor types to find optimal strategies.",
		ru = "Уязвимые места - определенные области на врагах, которые получают увеличенный урон при попадании.\n"
			.."\n"
			.."Основное расположение уязвимых точек:\n"
			.."	  • Голова (для подавляющего большинства гуманоидных врагов и не-боссов).\n"
			.."	  • Особые уязвимые зоны есть только у определённых чудовищ (например, спина Чудовища Нургла).\n"
			.."\n"
			.."Важная тактическая заметка:\n"
			.."	  Голова НЕ ВСЕГДА является лучшей целью. У некоторых тяжелобронированных врагов, таких как Крушители (Maulers) и Крестоносцы (Crushers), на голове броня типа Carapace (Панцирная). Против них попадание в корпус (броня Flak) или ноги (без брони) некоторым оружием может быть эффективнее.\n"
			.."\n"
			.."Преимущества уязвимых мест:\n"
			.."	  1. Увеличенный урон - Множитель значительно различается в зависимости от оружия.\n"
			.."	  2. Ошеломление - Часто вызывает дополнительное ошеломление.\n"
			.."	  3. Специальные эффекты - Могут активировать определённые благословения и таланты.\n"
			.."\n"
			.."Индикаторы уязвимых мест:\n"
			.."	  • Жёлтые цифры урона (основной индикатор).\n"
			.."	  • Другой звук попадания и реакция прицела.\n"
			.."\n"
			.."Проверка - это ключ:\n"
			.."	  Используйте Психаниум, чтобы проверить множители урона вашего оружия по уязвимым точкам против разных типов брони и найти оптимальную стратегию."
	},
	rending_ingame_description = {
		en = "Rending (Armor Penetration) - In the arsenals of the Imperium, this term denotes weapons or munitions specifically designed to tear through and ignore layers of protection. Increases YOUR damage against armored enemies.\n"
			.."\n"
			.."WHAT IT DOES: Each percentage of Rending allows 5% of your attack's damage to ignore the target's armor, treating it as Unarmored damage.\n"
			.."\n"
			.."HOW IT WORKS: It is a personal buff that only enhances your OWN attacks. It is most effective against Carapace armor.\n"
			.."\n"
			.."BENEFITS: Crucial for dealing with heavily armored enemies like Crushers. It can make weapons viable against armor that they normally struggle with.\n"
			.."\n"
			.."LIMITATIONS: Only works against Flak and Carapace armor types. Has diminishing returns on weapons with high innate armor penetration. Maximum armor reduction is capped at 100%.\n"
			.."\n"
			.."VERDICT: A must-have effect on high difficulties for dealing with elite armored enemies.",
		ru = "Пробивание брони - В арсеналах Империума этот термин обозначает оружие или боеприпасы, созданные специально для разрыва и игнорирования слоёв защиты. Увеличивает ВАШ урон по бронированным врагам.\n"
			.."\n"
			.."ЧТО ДЕЛАЕТ: Каждый процент Пробивания позволяет 5% урона от вашей атаки игнорировать броню цели, рассчитываясь как по небронированной цели.\n"
			.."\n"
			.."КАК РАБОТАЕТ: Это личное усиление, которое действует ТОЛЬКО на ваши атаки. Наиболее эффективно против панцирной брони (Carapace).\n"
			.."\n"
			.."ПОЛЬЗА: Критически важно для борьбы с тяжелобронированными целями, такими как Крушители. Может позволить оружию эффективно поражать броню, против которой оно обычно бесполезно.\n"
			.."\n"
			.."ОГРАНИЧЕНИЯ: Работает только против типов брони Флак и Карапас. Имеет убывающую отдачу на оружии с высоким врождённым пробитием. Максимальное снижение брони ограничено 100%.\n"
			.."\n"
			.."ВЫВОД: Обязательный эффект на высоких уровнях сложности для борьбы с элитной бронёй."
	},
	brittleness_ingame_description = {
		en = "Brittleness - Reduces an enemy's armor for EVERYONE.\n"
			.."\n"
			.."WHAT IT DOES: Applies a debuff stack on the enemy. Each stack (up to 8) reduces the target's armor rating by 5% for a short duration.\n"
			.."\n"
			.."HOW IT WORKS: It is a team-wide debuff. All subsequent attacks from you AND your allies deal increased damage to the debuffed enemy.\n"
			.."\n"
			.."BENEFITS: Incredibly powerful for coordinated teams. Fast-attacking weapons can quickly max out the debuff, letting heavy hitters finish the target.\n"
			.."\n"
			.."LIMITATIONS: Effect is temporary (usually 5 seconds). Some reports suggest it may not affect Psykers' Force damage. Maximum armor reduction is capped at 100%.\n"
			.."\n"
			.."VERDICT: The ultimate support tool for annihilating priority armored targets as a team.",
		ru = "Хрупкость - Снижает броню врага для ВСЕХ.\n"
			.."\n"
			.."ЧТО ДЕЛАЕТ: Накладывает на врага эффект-ослабление. Каждый стак (до 8) снижает показатель брони цели на 5% на короткое время.\n"
			.."\n"
			.."КАК РАБОТАЕТ: Это ослабление, действующее на всю команду. Все последующие атаки ОТ ВАС И ВАШИХ СОЮЗНИКОВ наносят увеличенный урон ослабленному врагу.\n"
			.."\n"
			.."ПОЛЬЗА: Невероятно мощно для слаженной команды. Быстрое оружие может быстро наложить максимум стаков, позволяя тяжелому оружию добить цель.\n"
			.."\n"
			.."ОГРАНИЧЕНИЯ: Эффект временный (обычно 5 секунд). Есть данные, что может не влиять на Силовой урон Псайкеров. Максимальное снижение брони ограничено 100%.\n"
			.."\n"
			.."ВЫВОД: Идеальный инструмент поддержки для быстрого уничтожения приоритетных бронированных целей командой."
	},
}

return ingame_descriptions