
-- xsSplained_mechanics_desc.lua
local mod = get_mod("xsSplained")

--[+ ++ЗАГРУЗКА ЦВЕТОВЫХ ФАЙЛОВ++ +]--
local xss_KWords, xss_Numbers, xss_KWords_ru

local function load_colors_for_descriptions()
	local success_kwords, result_kwords = pcall(function()
		return mod:io_dofile("xsSplained/Colors_Keywords_Numbers/xss_KWords")
	end)
	
	local success_numbers, result_numbers = pcall(function()
		return mod:io_dofile("xsSplained/Colors_Keywords_Numbers/xss_Numbers")
	end)
	
	local success_kwords_ru, result_kwords_ru = pcall(function()
		return mod:io_dofile("xsSplained/Colors_Keywords_Numbers/xss_KWords_ru")
	end)
	
	xss_KWords = success_kwords and result_kwords or {}
	xss_Numbers = success_numbers and result_numbers or {}
	xss_KWords_ru = success_kwords_ru and result_kwords_ru or {}
	
	return success_kwords and success_numbers
end

-- Загружаем цвета при инициализации файла
load_colors_for_descriptions()

local ingame_descriptions = {
	strength_ingame_description = {
		en = "STRENGTH (Power) - Increases your Melee combat effectiveness.\n"
			.."\n"
			.."Strength primarily affects:\n"
			.."   1. Damage – Higher Strength increases the raw Damage output of Melee weapons, making them deadlier against all enemy types.\n"
			.."   2. Stagger – Boosts the ability to interrupt, knock back, or Stun enemies, crucial for crowd control.\n" 
			.."   3. Cleave – Improves how many targets your attacks can hit in a single swing, allowing you to cut through hordes more efficiently.\n"
			.."\n"
			.."Why It Matters?\n"
			.."   - Melee-focused classes (e.g., Ogryn, Zealot) benefit the most, as Strength directly improves their close-quarters dominance.\n"
			.."   - Survivability – Stronger Stagger and Cleave help control enemy mobs, reducing incoming Damage.\n"
			.."\n"
			.."How to increase Strength?\n"
			.."   Use Blessings and Talents that boost Strength.",
		ru = "СИЛА (англ. Strength, устар. Power) - повышает вашу эффективность в ближнем бою.\n"
			.."\n"
			.."Сила в первую очередь влияет на:\n"
			.."   1. Урон – высокая Сила увеличивает чистый урон оружия ближнего боя, делая его более смертоносным против всех типов врагов.\n"
			.."   2. Ошеломление — увеличивает способность прерывать, отбрасывать или оглушать врагов, что крайне важно для контроля толпы.\n"
			.."   3. Рассечение — увеличивает количество целей, которые ваши атаки могут поразить за один удар, позволяя вам эффективнее прорубаться сквозь орды.\n"
			.."\n"
			.."Почему Сила важна?\n" 
			.."   - Наибольшую выгоду получают классы, ориентированные на ближний бой (например, Огрин и Изувер), поскольку Сила напрямую улучшает их доминирование в ближнем бою.\n"
			.."   - Выживаемость — Ошеломление и Рассечение помогают контролировать вражеских мобов, уменьшая входящий урон.\n"
			.."\n"
			.."Как увеличить Силу?\n"
			.."   Используйте Благословения и Таланты, которые повышают Силу.",
	},
	finesse_ingame_description = {
		en = "FINESSE - Increases the Weapon's Attack Speed and grants bonus to Critical Hits and Weak Spot Hits.\n"
			.."\n"
			.."Finesse primarily affects:\n"
			.."   1. Weak Spot Damage – Increases Damage dealt to enemy Weak spots.\n"
			.."   2. Critical Damage – Increases Damage from Critical hits.\n"
			.."   3. Attack Speed – Increases attack speed of Light and Heavy attacks.\n"
			.."\n"
			.."Why It Matters?\n"
			.."   - The biggest benefit comes from fast weapons (Combat blades, Dueling swords, Chainswords) as they tend to Critical Hits more often, greatly increasing the effectiveness of builds that rely on Critical Hits.\n"
			.."\n"
			.."How to increase Finesse?\n"
			.."   Use high-Finesse weapons, weapon Blessings or Talents.",
		ru = "ЛОВКОСТЬ (англ. Finesse) — повышает вашу эффективность в ближнем бою.\n"
			.."\n"
			.."Ловкость в первую очередь влияет на:\n"
			.."   1. Урон по уязвимым местам – увеличивает урон, наносимый по уязвимым местам противников.\n"
			.."   2. Критический урон – увеличивает урон от критических ударов.\n"
			.."   3. Скорость атаки – увеличивает скорость атаки лёгких и тяжёлых ударов.\n"
			.."\n"
			.."Почему Ловкость важна?\n"
			.."   - Наибольшее преимущество даёт быстрое оружие (боевые клинки, дуэльные мечи, цепные мечи), поскольку оно имеет тенденцию чаще наносить критические удары, значительно повышая эффективность билдов, полагающихся на критические удары.\n"
			.."\n"
			.."Как увеличить Ловкость?\n"
			.."   Используйте быстрое оружие, соответствующие Благословения оружия или Таланты.",
	},
	health_ingame_description = {
		en = "HEALTH determines your survivability — how much Damage you can take before being downed.\n"
			.."\n"
			.."Health is your actual life pool, and is slightly harder to restore during combat than Toughness. Your max Health varies by class.\n"
			.."\n"
			.."WOUND.\n"
			.."Your Health is divided into a number of segments, called Wounds. If you get downed, one of your Wounds will become Corrupted (indicated by a purple bar).\n"
			.."\n"
			.."Health Damage.\n"
			.."When Toughness breaks, attacks hurt Health directly. If your Health is reduced to 0, you go down, and need to be revived by Allies. In combat, Health is primarily restored only by Stimms, Medipack, and Med stations. There is no passive regeneration, so try not to lose it.\n"
			.."\n"
			.."Health Recovery:\n"
			.."   Medicae Stations: full restore.\n"
			.."   Medipack: full restore if not Corrupted.\n"
			.."\n"
			.."How to Increase Health?\n"
			.."Curios.\n"
			.."\n"
			.."CLASS HEALTH VALUES\n"
			.."________________________________\n"
			.."Class:       | Health: | +21% | +21% | +21% |\n"
			.."________________________________\n"
			.."Ogryn:      |      300 |    363 |  426 |   489 |\n"
			.."Zealot:      |      200 |    242 |  284 |   326 |\n"
			.."Arbites:    |      200 |     242 |  284 |   326 |\n"
			.."Veteran:   |       150 |     182 |   213 |   245 |\n"
			.."Psyker:     |       150 |     182 |   213 |   245 |\n"
			.."________________________________\n",
		ru = "ЗДОРОВЬЕ определяет сколько урона вы можете выдержать, прежде чем будете выведены из строя.\n"
			.."\n"
			.."Ваш запас здоровья немного сложнее восстановить во время боя, чем стойкость.\n"
			.."\n"
			.."РАНА.\n"
			.."Ваше здоровье разделено на несколько сегментов, называемых «ранами». Если вас убьют, одна из ваших ран закроется порчей (обозначается фиолетовым цветом).\n"
			.."\n"
			.."Урон здоровью.\n"
			.."Когда стойкость пробивают, атаки напрямую бьют по здоровье. Если здоровье падает до 0, вы падаете и вас нужно будет поднять вашим союзникам.\n"
			.."В бою Здоровье в основном восстанавливается только от стимуляторов, аптечек и медстанций. Пассивной регенерации нет, т.ч. старайтесь его не терять.\n"
			.."\n"
			.."Восстановление здоровья:\n"
			.."   Медицинские станции: полное восстановление.\n"
			.."   Медпаки: полное восстановление, если не поврежден.\n"
			.."\n"
			.."Как увеличить уровень Здоровья?\n"
			.."С помощью Редкостей, добавляющих проценты Здоровья.\n"
			.."\n"
			.."ПОКАЗАТЕЛИ ЗДОРОВЬЯ КЛАССОВ\n"
			.."___________________________________\n"
			.."Класс:       | Здоровье: | +21% | +21% | +21% |\n"
			.."___________________________________\n"
			.."Огрин:      |             300 |   363 |   426 |   489 |\n"
			.."Изувер:    |             200 |   242 |   284 |   326 |\n"
			.."Арбитр:    |             200 |   242 |   284 |   326 |\n"
			.."Ветеран:  |              150 |   182 |    213 |   245 |\n"
			.."Псайкер:  |              150 |   182 |    213 |   245 |\n"
			.."___________________________________\n",
	},
	toughness_ingame_description = {
		en = "TOUGHNESS - your personal damage-absorbing shield that protects your Health from most attacks.\n"
			.."\n"
			.."Unlike Health, Toughness can regenerate during combat.\n"
			.."\n"
			.."Damage Mitigation:\n"
			.."   1. Ranged Attacks: Toughness blocks 100% of ranged damage until depleted.\n"
			.."   2. Melee Attacks:\n"
			.."   - At 100% Toughness: Blocks 100% of melee damage.\n"
			.."   - Below 100% Toughness: You take partial Health damage from melee hits.\n"
			.."   - Special Attacks: Some enemies (Poxbursters, Snipers, Tox Flamers) bypass Toughness and damage Health directly.\n"
			.."\n"
			.."How to Increase Toughness?\n"
			.."Curios and Talents.",
		ru = "СТОЙКОСТЬ - ваш персональный щит, который защищает ваше здоровье от большинства атак."
			.."\n"
			.."\n"
			.."В отличие от здоровья, стойкость восстанавливается во время боя.\n"
			.."\n"
			.."Снижение урона:\n"
			.."   1. Атаки дальнего боя: стойкость блокирует 100% урона от таких атак до тех пор, пока не иссякнет.\n"
			.."   2. Атаки ближнего боя:\n"
			.."   - При 100% стойкости блокируется 100% урона ближнего боя.\n"
			.."   - Если уровень стойкости ниже 100%: Часть урона пройдёт по стойкости, остальной пройдёт по здоровью.\n"
			.."   - Специальные атаки: Урон некоторых врагов (Взрывун, Снайпер, Токс-огнемётчик) обходит стойкость и сразу бьёт по здоровью.\n"
			.."\n"
			.."Как увеличить стойкость?\n"
			.."Редкости и Таланты.",
	},
	stamina_ingame_description = {
		en = "STAMINA - governs your ability to perform defensive actions like blocking, pushing, and dodging.\n"
			.."\n"
			.."Stamina is represented by segmented bars and affects:\n"
			.."   1. Blocking - Each attack blocked consumes stamina based on the attack's strength\n"
			.."   2. Pushing - Performing push attacks consumes stamina\n" 
			.."   3. Dodging - Each dodge consumes a fixed amount of stamina\n"
			.."   4. Sprinting - Continuous sprinting drains stamina over time\n"
			.."\n"
			.."Why It Matters?\n"
			.."   - Proper stamina management is crucial for survival in melee combat\n"
			.."   - Running out of stamina leaves you vulnerable to enemy attacks\n"
			.."   - Different weapons have varying stamina consumption rates\n"
			.."\n"
			.."Stamina Regeneration:\n"
			.."   - Stamina regenerates automatically when not being used\n"
			.."   - Regeneration is faster when not in combat\n"
			.."   - Some talents and curios can improve stamina regeneration",
		ru = "ВЫНОСЛИВОСТЬ - определяет вашу способность выполнять защитные действия, такие как блокирование, толчки и уклонения.\n"
			.."\n"
			.."Выносливость представлена сегментированными полосами и влияет на:\n"
			.."   1. Блокирование - Каждая заблокированная атака потребляет выносливость в зависимости от силы атаки\n"
			.."   2. Толчки - Выполнение толчков потребляет выносливость\n"
			.."   3. Уклонения - Каждое уклонение потребляет фиксированное количество выносливости\n"
			.."   4. Спринт - Непрерывный спринт истощает выносливость со временем\n"
			.."\n"
			.."Почему это важно?\n"
			.."   - Правильное управление выносливостью крайне важно для выживания в ближнем бою\n"
			.."   - Истощение выносливости оставляет вас уязвимым для вражеских атак\n"
			.."   - Разное оружие имеет различную скорость потребления выносливости\n"
			.."\n"
			.."Восстановление выносливости:\n"
			.."   - Выносливость восстанавливается автоматически, когда не используется\n"
			.."   - Восстановление быстрее вне боя\n"
			.."   - Некоторые таланты и редкости могут улучшить восстановление выносливости",
	},
	cleave_ingame_description = {
		en = "Cleave determines how many enemies your attack can hit before losing effectiveness.\n"
			.."\n"
			.."Key aspects of Cleave:\n"
			.."   1. Target Limit - Maximum number of enemies an attack can damage\n"
			.."   2. Damage Falloff - Damage may decrease with each subsequent target\n"
			.."   3. Weapon Dependent - Different weapons have different cleave values\n"
			.."   4. Strength Bonus - Higher Strength increases cleave capability\n"
			.."\n"
			.."Why It Matters?\n"
			.."   - Essential for dealing with hordes effectively\n"
			.."   - High cleave weapons can control large groups of enemies\n"
			.."   - Affects your crowd control potential\n"
			.."\n"
			.."Weapon Examples:\n"
			.."   - High Cleave: Two-handed swords, power mauls\n"
			.."   - Low Cleave: Daggers, rapiers, single-target weapons",
		ru = "Рассечение — определяет, сколько врагов ваша атака может поразить до потери эффективности.\n"
			.."\n"
			.."Ключевые аспекты Рассечения:\n"
			.."   1. Лимит целей - Максимальное количество врагов, которых может повредить атака\n"
			.."   2. Спад урона - Урон может уменьшаться с каждой последующей целью\n"
			.."   3. Зависит от оружия - Разное оружие имеет разные значения рассечения\n"
			.."   4. Бонус силы - Высокая Сила увеличивает способность к рассечению\n"
			.."\n"
			.."Почему это важно?\n"
			.."   - Необходимо для эффективной борьбы с ордами\n"
			.."   - Оружие с высоким рассечением может контролировать большие группы врагов\n"
			.."   - Влияет на ваш потенциал контроля толпы\n"
			.."\n"
			.."Примеры оружия:\n"
			.."   - Высокое рассечение: Двуручные мечи, силовые булавы\n"
			.."   - Низкое рассечение: Кинжалы, рапиры, одноцелевое оружие",
	},
	crit_chance_ingame_description = {
		en = "CRITICAL CHANCE - determines the probability of landing critical hits.\n"
			.."\n"
			.."Critical Hits provide:\n"
			.."   1. Increased Damage - Typically 150% of normal damage\n"
			.."   2. Special Effects - Can trigger various blessings and talents\n"
			.."   3. Ignore Armor - Some critical hits bypass armor resistance\n"
			.."\n"
			.."Factors Affecting Critical Chance:\n"
			.."   1. Weapon Base - Each weapon has inherent critical chance\n"
			.."   2. Finesse - Higher finesse increases critical chance\n"
			.."   3. Blessings - Certain blessings boost critical chance\n"
			.."   4. Talents - Class talents can provide critical bonuses\n"
			.."   5. Weak Spot Hits - Some weak spot hits guarantee crits\n"
			.."\n"
			.."Critical Hit Indicators:\n"
			.."   - Different sound effect on hit\n"
			.."   - Visual effects (sparks, brighter hit markers)\n"
			.."   - Larger damage numbers",
		ru = "ШАНС КРИТИЧЕСКОГО УДАРА - определяет вероятность нанесения критических ударов.\n"
			.."\n"
			.."Критические удары обеспечивают:\n"
			.."   1. Увеличенный урон - Обычно 150% от обычного урона\n"
			.."   2. Специальные эффекты - Могут активировать различные благословения и таланты\n"
			.."   3. Игнорирование брони - Некоторые критические удары обходят сопротивление брони\n"
			.."\n"
			.."Факторы, влияющие на шанс крита:\n"
			.."   1. База оружия - Каждое оружие имеет присущий ему шанс крита\n"
			.."   2. Ловкость - Высокая ловкость увеличивает шанс крита\n"
			.."   3. Благословения - Некоторые благословения повышают шанс крита\n"
			.."   4. Таланты - Таланты класса могут предоставлять критические бонусы\n"
			.."   5. Попадания в уязвимые места - Некоторые попадания в уязвимые места гарантируют криты\n"
			.."\n"
			.."Индикаторы критического удара:\n"
			.."   - Другой звуковой эффект при попадании\n"
			.."   - Визуальные эффекты (искры, более яркие маркеры попадания)\n"
			.."   - Большие числа урона",
	},
	impact_ingame_description = {
		en = "IMPACT - increases the effectiveness of stagger on enemies.\n"
			.."\n"
			.."Stagger potential of an attack.\n"
			.."\n"
			.."   Each attack has an Impact number, it is checked vs the Stagger thresholds of the target and then picks a type of Stagger (light, medium, heavy) and scales duration/distance based on how far you exceed the threshold.\n"
			.."\n"
			.."More Impact equals more and longer control.",
		ru = "ВЫВЕДЕНИЕ ИЗ РАВНОВЕСИЯ - увеличивает эффективность ошеломления врагов.\n"
			.."\n"
			.."Потенциал ошеломления атаки.\n"
			.."\n"
			.."   Каждая атака имеет число выведения из равновесия, которое проверяется против порога ошеломления цели, а затем выбирает тип ошеломления (лёгкое, среднее, тяжелое) и масштабирует длительность/расстояние на основе того, насколько вы превышаете порог.\n"
			.."\n"
			.."Больше выведения из равновесия означает больший и долгий контроль.",
	},
	hitmass_ingame_description = {
		en = "HIT MASS - represents the resistance enemies provide against your attacks' cleave potential.\n"
			.."\n"
			.."Key Concepts:\n"
			.."   1. Enemy Resistance - Different enemies have different hit mass values\n"
			.."   2. Cleave Consumption - Each enemy hit consumes cleave based on their hit mass\n"
			.."   3. Attack Stopping - High hit mass enemies can stop your attack chain\n"
			.."\n"
			.."Enemy Hit Mass Examples:\n"
			.."   - Low: Poxwalkers, Groaners\n"
			.."   - Medium: Shooters, Bruisers\n"
			.."   - High: Maulers, Crushers, Monstrosities\n"
			.."\n"
			.."Strategic Importance:\n"
			.."   - Target selection matters - hitting high hit mass enemies first can waste cleave\n"
			.."   - Weapon choice - some weapons are better against high hit mass targets\n"
			.."   - Positioning - attack angles can affect how hit mass impacts your effectiveness",
		ru = "УДАРНАЯ МАССА - представляет сопротивление, которое враги оказывают против потенциала рассечения ваших атак.\n"
			.."\n"
			.."Ключевые концепции:\n"
			.."   1. Сопротивление врагов - Разные враги имеют разные значения ударной массы\n"
			.."   2. Потребление рассечения - Каждый пораженный враг потребляет рассечение на основе своей ударной массы\n"
			.."   3. Остановка атаки - Враги с высокой ударной массой могут остановить вашу цепочку атак\n"
			.."\n"
			.."Примеры ударной массы врагов:\n"
			.."   - Низкая: Чумные, Стонущие\n"
			.."   - Средняя: Стрелки, Громилы\n"
			.."   - Высокая: Крушители, Крестоносцы, Чудовища\n"
			.."\n"
			.."Стратегическая важность:\n"
			.."   - Выбор цели имеет значение - попадание по врагам с высокой ударной массой сначала может потратить рассечение\n"
			.."   - Выбор оружия - некоторое оружие лучше против целей с высокой ударной массой\n"
			.."   - Позиционирование - углы атаки могут влиять на то, как ударная масса влияет на вашу эффективность",
	},
	stagger_ingame_description = {
		en = "STAGGER means interrupting or knocking enemies back.\n"
			.."\n"
			.."Stagger Types:\n"
			.."   1. Light Stagger - Brief interruption, enemy recovers quickly\n"
			.."   2. Medium Stagger - Longer interruption, may cause stumbling\n"
			.."   3. Heavy Stagger - Knocks enemy down or sends them flying\n"
			.."   4. Infinite Stagger - Continuous stagger (e.g., from flamethrower)\n"
			.."\n"
			.."Benefits of Stagger:\n"
			.."   - Interrupts enemy attacks\n"
			.."   - Creates breathing room in combat\n"
			.."   - Sets up enemies for follow-up attacks\n"
			.."   - Can break enemy formations\n"
			.."\n"
			.."Stagger Sources:\n"
			.."   - Melee attacks (especially heavy attacks)\n"
			.."   - Certain ranged weapons\n"
			.."   - Explosives and grenades\n"
			.."   - Special abilities and talents",
		ru = "ОШЕЛОМЛЕНИЕ означает прерывание или отбрасывание врагов.\n"
			.."\n"
			.."Типы ошеломления:\n"
			.."   1. Легкое ошеломление - Краткое прерывание, враг быстро восстанавливается\n"
			.."   2. Среднее ошеломление - Более длительное прерывание, может вызвать спотыкание\n"
			.."   3. Тяжелое ошеломление - Сбивает врага с ног или отправляет его в полет\n"
			.."   4. Бесконечное ошеломление - Непрерывное ошеломление (например, от огнемета)\n"
			.."\n"
			.."Преимущества ошеломления:\n"
			.."   - Прерывает вражеские атаки\n"
			.."   - Создает передышку в бою\n"
			.."   - Подготавливает врагов для последующих атак\n"
			.."   - Может разрушать вражеские построения\n"
			.."\n"
			.."Источники ошеломления:\n"
			.."   - Атаки ближнего боя (особенно тяжелые атаки)\n"
			.."   - Некоторые виды дальнобойного оружия\n"
			.."   - Взрывчатка и гранаты\n"
			.."   - Особые способности и таланты",
	},
	weakspot_ingame_description = {
		en = "WEAK SPOTS - specific areas on enemies that take increased damage when hit.\n"
			.."\n"
			.."Common Weak Spot Locations:\n"
			.."   - Head (most humanoid enemies)\n"
			.."   - Back (some special enemies)\n"
			.."   - Glowing parts (certain elites and specialists)\n"
			.."   - Armor gaps (Crushers, Maulers)\n"
			.."\n"
			.."Weak Spot Benefits:\n"
			.."   1. Increased Damage - Typically 150-200% of normal damage\n"
			.."   2. Stagger - Often causes additional stagger\n"
			.."   3. Critical Chance - Some weak spot hits guarantee criticals\n"
			.."   4. Special Effects - Can trigger specific blessings and talents\n"
			.."\n"
			.."Weak Spot Indicators:\n"
			.."   - Different hit sound\n"
			.."   - Visual feedback (crosshair change, hit marker)\n"
			.."   - Larger, colored damage numbers",
		ru = "УЯЗВИМЫЕ МЕСТА - определенные области на врагах, которые получают увеличенный урон при попадании.\n"
			.."\n"
			.."Распространенные места уязвимых точек:\n"
			.."   - Голова (большинство гуманоидных врагов)\n"
			.."   - Спина (некоторые особые враги)\n"
			.."   - Светящиеся части (определенные элиты и специалисты)\n"
			.."   - Прорехи в броне (Крестоносцы, Крушители)\n"
			.."\n"
			.."Преимущества уязвимых мест:\n"
			.."   1. Увеличенный урон - Обычно 150-200% от обычного урона\n"
			.."   2. Ошеломление - Часто вызывает дополнительное ошеломление\n"
			.."   3. Шанс крита - Некоторые попадания в уязвимые места гарантируют криты\n"
			.."   4. Специальные эффекты - Могут активировать определенные благословения и таланты\n"
			.."\n"
			.."Индикаторы уязвимых мест:\n"
			.."   - Другой звук попадания\n"
			.."   - Визуальная обратная связь (изменение прицела, маркер попадания)\n"
			.."   - Большие, цветные числа урона",
	},
	rending_ingame_description = {
		en = "RENDING - increases effectiveness against armored enemies.\n"
			.."\n"
			.."Rending increases your armour penetration.\n"
			.."\n"
			.."Rending disregards Flak and Carapace armor modificators and uses the Base Damage instead for the Rending portion.\n"
			.."At 50% Rending, half the Damage calculates based on original armor type.",
		ru = "ПРОБИВАНИЕ (брони) - увеличивает эффективность против бронированных врагов.\n"
			.."\n"
			.."Пробивание брони увеличивает ваше проникновение брони.\n"
			.."\n"
			.."Пробивание брони игнорирует модификаторы противоосколочной и панцирной брони и использует базовый урон вместо части пробивания.\n"
			.."При 50% пробивания половина урона рассчитывается на основе исходного типа брони.",
	},
	brittleness_ingame_description = {
		en = "BRITTLENESS - increases effectiveness against armored enemies.\n"
			.."\n"
			.."Brittleness debuffs and reduces the enemy's armour.\n"
			.."\n"
			.."Brittleness disregards Flak and Carapace armor mods and uses the Base Damage instead for the Brittleness portion.\n"
			.."At 50% Brittleness, half the Damage will calculate based on original armor type.\n"
			.."\n"
			.."Brittleness is basically 'Rending' but for all future attacks plus your team also benefits from it.",
		ru = "ХРУПКОСТЬ (брони) - увеличивает эффективность против бронированных врагов.\n"
			.."\n"
			.."Хрупкость брони ослабляет и уменьшает броню врага.\n"
			.."\n"
			.."Хрупкость брони игнорирует модификаторы брони Флак и Карапас и использует базовый урон вместо части хрупкости.\n"
			.."При 50% хрупкости брони половина урона будет рассчитываться на основе исходного типа брони.\n"
			.."\n"
			.."Хрупкость брони - это 'пробивание брони', но для всех будущих атак, плюс ваша команда также получает от неё выгоду.",
	},
}

return ingame_descriptions
